#!/bin/bash

ROOTDIR=$(cd ${0%/*}/..; pwd)
XSLTsDIR=${ROOTDIR}/CXXtoXML/src/XSLTs
CXXTOXML=${ROOTDIR}/CXXtoXML/src/CXXtoXML

${CXXTOXML} $@ |
      xsltproc ${XSLTsDIR}/drop_prop_column.xsl - |
      xsltproc ${XSLTsDIR}/drop_prop_file.xsl -  |
      xsltproc ${XSLTsDIR}/reorder_decl.xsl -  |
      xsltproc ${XSLTsDIR}/add_symbols_elem.xsl -  |
      xsltproc ${XSLTsDIR}/add_globalsymbols_elem.xsl -  |
      xsltproc ${XSLTsDIR}/Program2XcodeProgram.xsl -  |
      xmllint --format - 
